# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "docs", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: cn
permalink: /:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: http://cn.yizeng.me # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Yi Zeng
description: "Yi Zeng 的中文版个人网站"
keywords: 'yizeng,个人网站,博客,软件,开发,测试,基督城,新西兰,jekyll'
author:
  name: Yi Zeng
  job_title:
  location:
  email: yi.zeng.dev@gmail.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/yizeng/
    - name: instagram
      url: https://www.instagram.com/yizeng.me
    - name: linkedin
      url: https://www.linkedin.com/in/yizengnz/
    - name: stackoverflow
      url: https://stackoverflow.com/users/1177636/yi-zeng
    - name: twitter
      url: 
    - name: vk
      url: https://vk.com/yi.zeng
home:
  h1: Yi Zeng
  h2: Software Engineer
  h3: Christchurch, New Zealand
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License
  cc_license_image: /assets/images/theme/cc-by-sa.png # Choose one at https://creativecommons.org/choose/
  footer_content: 本博客译自 <a href="http://yizeng.me/blog" target="_blank">yizeng.me/blog</a>

disqus:
  shortname: yizeng-cn
  public_key: ULZ0b9TFdfCUJSKQd4WCKv2v3u25YoG7YG8zXPewkWrT35lZ0Se9YnxLzoV6VM8W
google_analytics: 'UA-42466615-2'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
