# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en
permalink: /blog/:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://yizeng.github.io/jekyll-theme-simple-texture
title: Simple Texture
description: "A gem-based responsive simple texture styled Jekyll theme."
keywords: 'jekyll,theme,gem-based,blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/yizeng/jekyll-theme-simple-texture
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  h1: Simple Texutre
  h2: A gem-based responsive simple texture styled Jekyll theme
  h3:
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License
  cc_license_image: /assets/images/theme/cc-by-sa.png # Choose one at https://creativecommons.org/choose/
  footer_content: A gem-based responsive simple texture styled Jekyll theme.

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
